import * as cdk from 'aws-cdk-lib';
import * as ec2  from 'aws-cdk-lib/aws-ec2';
import * as rds  from 'aws-cdk-lib/aws-rds';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as s3  from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';
import * as path from 'path';

export interface WhatsAppStackProps extends cdk.StackProps {
  stageName: 'dev' | 'prod';
  dbInstanceClass: string;
  lambdaMemoryMb: number;
  multiAz: boolean;
}

export class WhatsAppStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: WhatsAppStackProps) {
    super(scope, id, props);

    const { stageName, dbInstanceClass, lambdaMemoryMb, multiAz } = props;
    const prefix = `whatsapp-${stageName}`;

    // ─────────────────────────────────────────────────────────────────────────
    // 1. VPC  (Lambda + RDS live in the same VPC)
    // ─────────────────────────────────────────────────────────────────────────
    const vpc = new ec2.Vpc(this, 'Vpc', {
      vpcName: `${prefix}-vpc`,
      maxAzs: multiAz ? 3 : 2,
      natGateways: stageName === 'prod' ? 1 : 0,  // NAT costs money; skip in dev
      subnetConfiguration: [
        { name: 'Public',   subnetType: ec2.SubnetType.PUBLIC,             cidrMask: 24 },
        { name: 'Private',  subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS, cidrMask: 24 },
        { name: 'Isolated', subnetType: ec2.SubnetType.PRIVATE_ISOLATED,    cidrMask: 24 },
      ],
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 2. Security Groups
    // ─────────────────────────────────────────────────────────────────────────
    const lambdaSg = new ec2.SecurityGroup(this, 'LambdaSg', {
      vpc,
      securityGroupName: `${prefix}-lambda-sg`,
      description: 'Lambda function security group',
      allowAllOutbound: true,
    });

    const dbSg = new ec2.SecurityGroup(this, 'DbSg', {
      vpc,
      securityGroupName: `${prefix}-db-sg`,
      description: 'RDS PostgreSQL security group',
      allowAllOutbound: false,
    });

    // Only allow Lambda → RDS on port 5432
    dbSg.addIngressRule(lambdaSg, ec2.Port.tcp(5432), 'Lambda to RDS');

    // ─────────────────────────────────────────────────────────────────────────
    // 3. Secrets Manager — store WhatsApp tokens & DB password securely
    // ─────────────────────────────────────────────────────────────────────────
    const whatsAppSecret = new secretsmanager.Secret(this, 'WhatsAppSecret', {
      secretName: `${prefix}/whatsapp-config`,
      description: 'WhatsApp Cloud API credentials',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({
          WHATSAPP_ACCESS_TOKEN:         'REPLACE_AFTER_DEPLOY',
          WHATSAPP_PHONE_NUMBER_ID:      'REPLACE_AFTER_DEPLOY',
          WHATSAPP_BUSINESS_ACCOUNT_ID:  'REPLACE_AFTER_DEPLOY',
          WHATSAPP_APP_SECRET:           'REPLACE_AFTER_DEPLOY',
          WHATSAPP_WEBHOOK_VERIFY_TOKEN: 'REPLACE_AFTER_DEPLOY',
          WHATSAPP_OTP_TEMPLATE_NAME:    'authentication_otp',
          JWT_SECRET:                    'REPLACE_AFTER_DEPLOY',
          INTERNAL_API_KEY:              'REPLACE_AFTER_DEPLOY',
          ADMIN_SEED_SECRET:             'REPLACE_AFTER_DEPLOY',
        }),
        generateStringKey: '_placeholder',  // won't be used
        excludePunctuation: false,
      },
    });

    // DB password secret (auto-generated by CDK)
    const dbSecret = new secretsmanager.Secret(this, 'DbSecret', {
      secretName: `${prefix}/db-password`,
      generateSecretString: {
        excludePunctuation: true,
        passwordLength: 32,
      },
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 4. RDS PostgreSQL (Free Tier: db.t3.micro, 20 GB, no Multi-AZ)
    // ─────────────────────────────────────────────────────────────────────────
    const dbSubnetGroup = new rds.SubnetGroup(this, 'DbSubnetGroup', {
      description: `${prefix} DB subnet group`,
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
    });

    const dbInstance = new rds.DatabaseInstance(this, 'Database', {
      instanceIdentifier: `${prefix}-db`,
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_15_4,
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.T3,
        ec2.InstanceSize.MICRO   // Free Tier eligible
      ),
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      subnetGroup: dbSubnetGroup,
      securityGroups: [dbSg],
      credentials: rds.Credentials.fromPassword(
        'postgres',
        dbSecret.secretValue
      ),
      databaseName: 'whatsapp_db',
      multiAz: multiAz,
      allocatedStorage: 20,  // GB — Free Tier limit
      maxAllocatedStorage: stageName === 'prod' ? 100 : 20,
      storageEncrypted: true,
      backupRetention: cdk.Duration.days(stageName === 'prod' ? 7 : 1),
      deleteAutomatedBackups: stageName !== 'prod',
      removalPolicy: stageName === 'prod' ? cdk.RemovalPolicy.RETAIN : cdk.RemovalPolicy.DESTROY,
      // Enable auto minor version upgrades
      autoMinorVersionUpgrade: true,
      // Performance insights (free for t3.micro)
      enablePerformanceInsights: true,
      performanceInsightRetention: rds.PerformanceInsightRetention.DEFAULT,
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 5. Lambda Function
    // ─────────────────────────────────────────────────────────────────────────

    // Lambda execution role
    const lambdaRole = new iam.Role(this, 'LambdaRole', {
      roleName: `${prefix}-lambda-role`,
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaVPCAccessExecutionRole'),
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });

    // Allow Lambda to read secrets
    whatsAppSecret.grantRead(lambdaRole);
    dbSecret.grantRead(lambdaRole);

    // CloudWatch log group
    const logGroup = new logs.LogGroup(this, 'LambdaLogGroup', {
      logGroupName: `/aws/lambda/${prefix}-handler`,
      retention: stageName === 'prod' ? logs.RetentionDays.ONE_MONTH : logs.RetentionDays.ONE_WEEK,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // Lambda function (deploys ../lambda/lambda.zip built by `npm run package`)
    const lambdaFn = new lambda.Function(this, 'WhatsAppLambda', {
      functionName: `${prefix}-handler`,
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../lambda/dist')),
      memorySize: lambdaMemoryMb,
      timeout: cdk.Duration.seconds(30),
      role: lambdaRole,
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      securityGroups: [lambdaSg],
      logGroup,
      environment: {
        NODE_ENV: stageName === 'prod' ? 'production' : 'development',
        // DB connection string built from RDS endpoint + secret
        DATABASE_URL: `postgresql://postgres:${dbSecret.secretValue.unsafeUnwrap()}@${dbInstance.instanceEndpoint.hostname}:5432/whatsapp_db`,
        // WhatsApp config: loaded from Secrets Manager at runtime (see note below)
        // For simplicity here we reference the secret ARN; in production
        // use a Lambda extension or fetch with AWS SDK at cold-start.
        WHATSAPP_SECRET_ARN: whatsAppSecret.secretArn,
        // These are set by you after deploying (update the Lambda env vars in console)
        WHATSAPP_ACCESS_TOKEN:         'SET_VIA_SECRETS_MANAGER',
        WHATSAPP_PHONE_NUMBER_ID:      'SET_VIA_SECRETS_MANAGER',
        WHATSAPP_BUSINESS_ACCOUNT_ID:  'SET_VIA_SECRETS_MANAGER',
        WHATSAPP_APP_SECRET:           'SET_VIA_SECRETS_MANAGER',
        WHATSAPP_WEBHOOK_VERIFY_TOKEN: 'my-verify-token',
        JWT_SECRET:                    'SET_VIA_SECRETS_MANAGER',
        INTERNAL_API_KEY:              'SET_VIA_SECRETS_MANAGER',
        ADMIN_SEED_SECRET:             'SET_VIA_SECRETS_MANAGER',
        OTP_EXPIRY_MINUTES:            '10',
        OTP_MAX_ATTEMPTS:              '3',
      },
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 6. API Gateway (REST)
    // ─────────────────────────────────────────────────────────────────────────
    const api = new apigateway.LambdaRestApi(this, 'Api', {
      restApiName: `${prefix}-api`,
      handler: lambdaFn,
      proxy: true,                   // all routes → Lambda
      deployOptions: {
        stageName,
        loggingLevel: apigateway.MethodLoggingLevel.INFO,
        dataTraceEnabled: false,
        throttlingRateLimit: 100,
        throttlingBurstLimit: 200,
      },
      defaultCorsPreflightOptions: {
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
        allowMethods: apigateway.Cors.ALL_METHODS,
        allowHeaders: ['Content-Type', 'Authorization', 'X-Api-Key'],
      },
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 7. Admin UI — Static site on S3 + CloudFront
    // ─────────────────────────────────────────────────────────────────────────
    const adminBucket = new s3.Bucket(this, 'AdminUiBucket', {
      bucketName: `${prefix}-admin-ui`,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    const distribution = new cloudfront.Distribution(this, 'AdminUiCdn', {
      comment: `${prefix} Admin UI`,
      defaultBehavior: {
        origin: new origins.S3Origin(adminBucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,  // dev: no cache
      },
      defaultRootObject: 'index.html',
      errorResponses: [
        { httpStatus: 403, responseHttpStatus: 200, responsePagePath: '/index.html' },
        { httpStatus: 404, responseHttpStatus: 200, responsePagePath: '/index.html' },
      ],
    });

    // Deploy admin-ui folder to S3
    new s3deploy.BucketDeployment(this, 'AdminUiDeploy', {
      sources: [s3deploy.Source.asset(path.join(__dirname, '../../admin-ui'))],
      destinationBucket: adminBucket,
      distribution,
      distributionPaths: ['/*'],
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 8. Outputs — shown after `cdk deploy`
    // ─────────────────────────────────────────────────────────────────────────
    new cdk.CfnOutput(this, 'ApiUrl', {
      description: 'API Gateway URL — set this as VITE_API_URL in admin-ui',
      value: api.url,
    });

    new cdk.CfnOutput(this, 'AdminUiUrl', {
      description: 'Admin Dashboard URL',
      value: `https://${distribution.distributionDomainName}`,
    });

    new cdk.CfnOutput(this, 'WhatsAppWebhookUrl', {
      description: 'Set this URL in Meta Developer Portal → WhatsApp → Webhooks',
      value: `${api.url}webhook`,
    });

    new cdk.CfnOutput(this, 'DbEndpoint', {
      description: 'RDS endpoint (internal — only reachable from Lambda)',
      value: dbInstance.instanceEndpoint.hostname,
    });

    new cdk.CfnOutput(this, 'WhatsAppSecretArn', {
      description: 'Update this secret in AWS Secrets Manager with your WhatsApp credentials',
      value: whatsAppSecret.secretArn,
    });

    new cdk.CfnOutput(this, 'LambdaFunctionName', {
      description: 'Lambda function name — use this to run DB migrations',
      value: lambdaFn.functionName,
    });
  }
}
